### ISSUE TITLE
Button to add new shields or off-hand weapons is missing

### ISSUE THREAD

**Issue by dyvim** [Plushtoast/TDE-Roll20-Official#84]
The button that allow you to add shields or off-hand weapons in your inventory is missing

![image](https://user-images.githubusercontent.com/8790994/140431828-2b80231b-fd8f-4608-88e0-2d54a13cbd6f.png)

**Comment by Plushtoast** [comment]
It's removed on purpose.
Add a normal weapon and set the offhand attribute

**Comment by dyvim** [comment]
ok. not very intuitive but it's ok.

**Comment by Plushtoast** [comment]
Well yes roll20 is not very intuitive.
The weapons have been changed so they can be imported via the upcoming compendium and can be switched betweend hands easily. But by default a new row can only have one default value for offhand or not. That means if the button would be there it would be added to the mainhands instead. Which is not very intuitive as well.
So I would have to create an entirely different button, which is not available by default. 
And I am kind of sick working against roll20 defaults all the time...so that#s how it is.
